### ISSUE TITLE
NavMeshAgent no way to set AgentTypeID in Normal Editor

### ISSUE THREAD

**Issue by JBentleyHemlock** [Unity-Technologies/NavMeshComponents#10]
Currently there is no way to set which AgentTypeID that a NavMeshAgent uses unless you go to the Editor's Debug mode, select the ID from the NavMeshSurface and paste it into the NavMeshAgent.

Needs a drop down selection.

**Comment by JBentleyHemlock** [comment]
Also, there is no way to get/set the NavMeshAgent AgentTypeID value in code

**Comment by Bunzaga** [comment]
I also ran into this.  I originally wanted to use the Physics collision matrix to allow nav mesh agents to pass through each other, but since this seems to have been broken for quite a while now, I thought to change the agent type through code, so I could have very thin agents or thicker ones.  This also isn't an option, so for now, I guess I'll create a separate Prefab.

**Comment by jakobhu** [comment]
expecting it to land with 5.6.0p1 (exposing the agentTypeID to scripting API)
