### ISSUE TITLE
NavmeshAgent player not parallel to slope of hill when moving over hill

### ISSUE THREAD

**Issue by sandip-narwade** [Unity-Technologies/NavMeshComponents#104]
NavmeshAgent player not parallel to slope of hill when moving over hill. On plane surface its going smoothly. Please help me to solve below question.

[Question](https://answers.unity.com/questions/1568884/navmeshagent-player-not-parallel-to-slope-of-hill-1.html)

**Comment by turadr** [comment]
Use a physics raycast to get the normal of the ground mesh at the position of the player and manually orient its "up" axis to match that normal vector. Make sure you set `updateUpAxis` property to "false" for your NavMeshAgent otherwise the system will override any "vertical" orientation you give it.
