### ISSUE TITLE
NavMesh Modifier or NavMesh Modifier Volume Modifying the AreaType of the NavMesh failed

### ISSUE THREAD

**Issue by vovgou** [Unity-Technologies/NavMeshComponents#109]
Using NavMesh Modifier or NavMesh Modifier Volume to modify NavMesh, I want to change the AreaType of a part of the area to the AreaType of the smaller cost value, but it does not work,If you change from a smaller value to a bigger value, it works fine.Can you tell me why this is? Thanks!

For example: I have a big map, the cost of the road in the map is 1, and the cost of the wild is 3, and the cost of the water is 5. By default, I use the AreaType with a cost value of 3. With the NavMesh Modifier, I can successfully modify the AreaType of the water area, but I can't successfully modify the AreaType of  the road area.

When I put the Y coordinate of the mesh with the NavMesh Modifier script higher than the Y coordinate of the map's mesh by 0.02, they all work fine.

**Comment by pryankster** [comment]
This is old, and I hope you've solved your problem by now , but for those trying to figure it out, I seem to have stumbled upon a fix.  I was trying to make a levelcrossing for some train tracks.  I wanted my agent to prefer using the level crossing, if they were close enough to it, rather than just crossing the tracks.  My initial attempt had a NavMeshModifierVolume set to "walkable" (cost 1), to override the "TrainTrack" area (cost 100).  However, when the NavMesh was built, the "TrainTrack" area showed through where the modifier volume was located.    To solve the problem, I made a new area "LevelCrossing" (cost 1) which was further down the area list from the "TrainTrack" area.  This seems to allow the override to happen.  I don't know if this is planned behavior, but if it is, it should probably be documented :-)

**Comment by turadr** [comment]
I think the following explanation from the manual page about [Area Types](https://docs.unity3d.com/Manual/nav-AreasAndCosts.html) will help: 
> If several objects of different area types are overlapping, the resulting navmesh area type will generally be the one with the highest index. There is one exception however: Not Walkable always takes precedence. Which can be helpful if you need to block out an area.
