### ISSUE TITLE
The SamplePosition function does not return the closest point on navmesh surface

### ISSUE THREAD

**Issue by ThuanDoVan** [Unity-Technologies/NavMeshComponents#152]
I am finding a path from the blue square to the red square. I used **NavMesh.SamplePosition** function to get their point on the navmesh surface. Then I use **NavMesh.CalculatePath** to get the path.

But some case, The SamplePosition return the wrong point. I captured a case that this bug happened:
![Screen Shot 2020-02-06 at 5 38 56 PM](https://user-images.githubusercontent.com/24400573/73930319-e80db580-4908-11ea-893a-7a619052532b.png)
![Screen Shot 2020-02-06 at 5 38 40 PM](https://user-images.githubusercontent.com/24400573/73930327-ea700f80-4908-11ea-8b31-c2c19dcedcf7.png)

**Comment by turadr** [comment]
This issue is not related to the NavMesh Components themselves. Instead it seems to be a problem with the functionality of the navigation queries. It's best to send that to us through the Bug Reporter in the Unity editor.

It might have been fixed already along with the solution for this other case https://issuetracker.unity3d.com/issues/a-navmeshagent-gameobject-teleports-to-a-near-navmeshsurface-when-collided-with-a-moving-navmeshobstacle .
