### ISSUE TITLE
Some gameobjects ignored

### ISSUE THREAD

**Issue by dirkson** [Unity-Technologies/NavMeshComponents#16]
Some gameobjects using particular models appear to be entirely ignored by the navmesh baker.

All models EXCEPT the diagonal cliffs in this pack ( https://www.assetstore.unity3d.com/en/#!/content/67289 ) do not interact with the new navmesh surface baker - Nav Mesh Surface finds no walkable or unwalkable areas on them whatsoever. They DO bake without issue in the old 'legacy' section of the navigation system.

I've tried differing rotations, scales, and translations. I've tried switching the nav mesh's "Use Geometry" to both "render meshes" and "physics colliders". I've tried various voxel and tile sizes. I've created a test scene with nothing but a single plane and two cliffs. No settings appear to affect the issue.

I haven't been able to find any other groups of assets sharing the issue, but I haven't looked on more than a handful.

Please let me know if any additional info would be helpful.

Cheers!

**Comment by dirkson** [comment]
After a kind soul took pity on me in the IRC channel, we tracked this issue down to a permissions issue with the asset import - If the asset's import setting "Read/Write Enabled" is disabled, the model will function in the old nav system, but not the new one.

I doubt this needs much in the way of correcting on your end, but I figured I'd leave the issue here for future generations to google or something.

Cheers!

**Comment by jakobhu** [comment]
Thanks for the update - you should've seen an error in the console in the Unity editor:
`RuntimeNavMeshBuilder. Source Mesh does not allow read access: X`
where `X` is the name of the ignored input source.

The old bake system completely ignores this because in the editor (old system available in editor only) the mesh can be accessed even when the model is imported without "Read/Write Enabled"
