### ISSUE TITLE
NavMeshLink from Agent?

### ISSUE THREAD

**Issue by Southgrove-zz** [Unity-Technologies/NavMeshComponents#34]
There doesn't seem to be any way to find which NavMeshLink is being "stepped on" by an Agent.

`agent.currentOffMeshLinkData` has some of the data, but no reference to the GameObject.

Would be nice to at least be able to get the Area set for the NavMeshLink. Kinda hard to make different type of transitions for links at the moment, unless you make trigger areas and such. But that's messy.

**Comment by jakobhu** [comment]
The reason is that the `currentOffMeshLinkData` contains a reference to an `OffMeshLink` component  (which the `NavMeshLink` isn't - being a low-level component).
You can instead use this:
```
var link = (UnityEngine.AI.NavMeshLink)navAgent.navMeshOwner;
if (link)
  Debug.Log("Agent is on link ", link);
```

Which can also be used for `NavMeshSurface` - and customized to your needs.
That is - the `.owner` reference of type `UnityEngine.Object` and can be specified per `NavMeshLinkInstance` and `NavMeshDataInstance`

Also: to get the mask of the current polygon/link - you can use the agents 'SamplePathPosition' api with a distance of 0 (the hit return struct will contain the area mask).

**Comment by Southgrove** [comment]
Ooh, right. I've completely missed the navMeshOwner property. Thanks for the help!
Must say, I'm really digging these new navmesh components.

The less stuff that's hard coupled to scenes the better. =)
