### ISSUE TITLE
NavMeshSurface has no SetBuildSettings

### ISSUE THREAD

**Issue by kristofgiber** [Unity-Technologies/NavMeshComponents#49]
In my game you can resize the game area quite a lot so I can't use the same Navmesh Agent radius settings for all scaling, I'd need to adjust this Navmesh build setting during runtime. I've noticed that I can access this by

`NavMeshBuildSettings navSettings = GetComponent<NavMeshSurface>().GetBuildSettings();`

and then modify it 

`navSettings.agentRadius = 0.15f;`

But there is no way to re-assign these new settings to the Navmesh surface before building it.

`GetComponent<NavMeshSurface>().BuildNavMesh(); `

Is there a workaround or can you add a method to change the build settings?

Thanks

**Comment by kristofgiber** [comment]
I've noticed I can just add a new agent type in the Navmesh settings and set that in the NavMeshSurface so that's a good workaround although this way I can only have a few predefined agent radius values that I create agents for, rather than setting the radius to exactly match the game's current scaling, but that's okay.

**Comment by BlackRece** [comment]
It would be beneficial to be able to set build settings rather than just get the build settings without the ability to apply custom settings. The current work-around to have a game object in the scene with the required navmesh settings applied via the inspector is not very good for those of us trying to add navmeshes programmatically.
