### ISSUE TITLE
Static navmesh covers better than runtime navmesh

### ISSUE THREAD

**Issue by joshFive** [Unity-Technologies/NavMeshComponents#62]
The scenario is, in testing, I'm using floating island demo scene. I have a bridge that is placed in the scene during the editing phase, and is baked into the navmesh, the mesh provides great coverage. If I take that same prefab bridge and place it during runtime, the navmesh coverage is created, however it's unusable as the ends are disconnected.

**Comment by turadr** [comment]
@kuyote Could you share with us a picture showing the problem?

**Comment by kuyote** [comment]
here are images:

 [https://imgur.com/a/L3i3W](url)

**Comment by kuyote** [comment]
Baked:
<img width="1368" alt="navmesh_baked" src="https://user-images.githubusercontent.com/6653532/35635859-40cafc94-0664-11e8-90e4-3c390954ce2b.png">

Runtime:
<img width="1368" alt="navmesh_runtime" src="https://user-images.githubusercontent.com/6653532/35635865-46fab046-0664-11e8-92fe-a6c32ee8c6bf.png">

**Comment by kuyote** [comment]
I've added a plane over the bridge in an attempt to see if I can get it working. It's still not working properly. The capsule unit is scripted to move to the cube, when I start the game, It goes to the closest section of the prebaked navmesh and stops there.
<img width="1368" alt="navmesh_notworking" src="https://user-images.githubusercontent.com/6653532/35647035-248feda6-0686-11e8-887b-a95cf400099e.png">

**Comment by turadr** [comment]
When you bake offline (from the Navigation window) then the parameters of the **Baked Agent Size** are taken into consideration (step height=1.32, max slope =45, etc.).
When you bake at runtime the parameters from the _Agents_ tab are taken into consideration, for the _Humanoid_ type of agent (step height=0.87, max slope=48, radius=0.55, height=1.5, etc.).
Because the values you set to those parameters are not the same you get different results. Please try setting those values to be the same and report back if you still get a difference.
