### ISSUE TITLE
Package Manager version

### ISSUE THREAD

**Issue by mdawsonuk** [Unity-Technologies/NavMeshComponents#67]
Hi,

Will this be made available through the Unity 2018.1 package manager? If not, this would be really useful to help reduce code within repositories and make it more accessible/easier to update.

-Matt

**Comment by purple-movies** [comment]
Hey Matt, 
I suggested something similar in my issue https://github.com/Unity-Technologies/NavMeshComponents/issues/60

If the `Assets/NavMeshComponents` directory was in it's own repository we could include it as a Git submodule in our projects.

**Comment by Stormy102** [comment]
This is less git submodules for us, but the upcoming package manager which acts like NuGet for Unity. Means the code isn’t even included in our own distributable binaries.

**Comment by xCyborg** [comment]
Is there a package id to try this with packman?

**Comment by xCyborg** [comment]
Answer please?

**Comment by turadr** [comment]
NavMeshComponents will be definitely turned into a package but not in the next few months.

**Comment by bitinn** [comment]
@turadr Just wondering the status on this request, is it due to lack of resource? Anything users can do to help?

(Even releasing this as a preview package, or uploading `.package` in the release tab, is better than no package.)

**Comment by turadr** [comment]
We've previously postponed transitioning NavMeshComponents into a package due to limitations in the publishing workflow. Recently that process has been simplified and we're evaluating again if it's ready to allow for easy package maintenance. I don't have other news about it yet.

I think users cannot help at this stage because the workflow is internal as far as I know.

**Comment by xCyborg** [comment]
WOW! 1 year since this issue opened up, and still no package, even better, not much development except compatibility with newer versions of Unity.

Here is a suggestion : since there's not much development going on, why don't you scrap the whole package idea and integrate the Components directly into the Editor?

**Comment by KichangKim** [comment]
Agreed, NavMeshComponents should be managed via Package Manager or included directly in UnityEngine binary. Why this library is only separated from Packages? Is there any technical issue?

**Comment by Sonorpearl** [comment]
Would be realy nice.

**Comment by Arugin** [comment]
Please?

**Comment by Stormy102** [comment]
Looking at the components code there are Assembly Definitions which have been created for the project (https://github.com/Unity-Technologies/NavMeshComponents/tree/master/Assets/NavMeshComponents/Scripts). I just don't see how this can take a year... very disappointing and slow.

**Comment by bitinn** [comment]
Unity 2019.x allows custom packages AFAIK, someone could take a step to fork and package this :)

**Comment by Stormy102** [comment]
Hey all,

We took the liberty of forking it and taking their work which they have done on the build/package branch to make our own fork. As some of you may know, the Unity 2019.3 Alpha allows you to insert packages via their Git URL. So we decided to fork and package the Unity NavMesh Components. If you want to add the components in 2019.3 Alpha, click on the + symbol on the top left of the package manager and then select "Add package from git URL...". Paste in `https://github.com/DarkWindowStudios/NavMeshComponents.git` and the package will be added, showing up under "Unity Navmesh components". If anyone has any issues with the package directly, create an issue there, otherwise please make issues on the official Unity repo and refrain from making them on ours.

Cheers,
-Matt

**Comment by xCyborg** [comment]
Any new features being developed here?

**Comment by ShivamMukherjee** [comment]
@turadr really wish to see this happen!

**Comment by turadr** [comment]
> 
> 
> @turadr really wish to see this happen!

It is being worked on. https://github.com/Unity-Technologies/NavMeshComponents/issues/172#issuecomment-741714518

**Comment by turadr** [comment]
It is now an experimental package for Unity 2019.4 or newer. https://github.com/Unity-Technologies/NavMeshComponents/issues/172#issuecomment-808105998
