### ISSUE TITLE
Lag On Path finding.

### ISSUE THREAD

**Issue by SeiferCleric** [Unity-Technologies/NavMeshComponents#79]
Hey. I tested NavMeshSurface on a very simple scene. Everything bakes perfectly and the navmesh looks fine (almost an exact duplicate of the one I had with standard unity baking).  However there is definitely a difference in performance, my AI and character lags/stops every few steps when calculating their path. Am I doing something wrong? O I should mention I cleared the previous navmesh, leaving only the one generated by the NavMeshSurface.

**Comment by turadr** [comment]
I don't see any reason for having a difference in performance because both the NavMeshSurface and the static scene baking produce the exact same type of data, which is then used in one unique way by the pathfinding and navigation logic. There might be a slight difference in the shape of the resulting NavMesh, depending on the position of the NavMeshSurface. If it is placed at (0,0,0) then it should be equivalent to the static baking. 
Are you rebuilding the NavMesh at runtime? Please note that if the NavMesh surface is removed and added to the system due to calling repeatedly `BuildNavMesh()`, then the agent stops and recalculates the path once for every of those calls.
Has anything else changed in your game logic that causes the agent to recalculate its path?

**Comment by SeiferCleric** [comment]
Hey, I'm not baking at runtime. I tested it again, as you suggested I place the NavMeshSurace at (0,0,0), it definitely generates more vertices with NavMeshSurface (I've attached images showing the difference). I also haven't changed any game logic while testing both methods.

![screenshot 2018 04 20 10 51 58](https://user-images.githubusercontent.com/23035837/39042097-55a86390-448a-11e8-9735-60ae3a2b5914.png)
![screenshot 2018 04 20 10 53 31](https://user-images.githubusercontent.com/23035837/39042098-55fbd976-448a-11e8-8882-c4698567a1ab.png)

**Comment by turadr** [comment]
It looks like the NavMeshSurface does not ignore the poles of the surrounding rails and thus extends the NavMesh over their small connecting platform. 
Are the rails set as "Navigation Static" and "Not Walkable" in the Navigation > Object window?
![image](https://user-images.githubusercontent.com/9038468/39054446-f58fa7fc-44b1-11e8-8f49-679c943c43cc.png)
Attach a NavMeshModifier component to the rail objects and set it to Override Area and Area Type = Not Walkable. Bake again and let me know if the NavMeshes are now identical.

**Comment by turadr** [comment]
Or, actually, maybe the rails were not Navigation Static, so they were not taken into consideration. In this case set the NavMeshModifier of the rails to "Ignore From Build" and thus the NavMesh will keep away from the edge of the hexagonal-platform.
