### ISSUE TITLE
Performance regarding navmesh generation with run time baking

### ISSUE THREAD

**Issue by ukwd** [Unity-Technologies/NavMeshComponents#95]
When using navmesh modifier, i noticed the only way it takes affect is to generate the whole navmesh again. Why can't we just update the specific part of the graph that the new modifier overlaps ?

Does this mean it is literally regenerating the entire graph? Or does it just update the nodes underneath it's colliders/transforms and there for is actually only updating relevant portions of the navmesh?

If its generating the whole navmesh all over again its performance benefits are non existent when the graph is used for a large map. Since there is no information on how it regenerates the graph in terms of optimisation could you please give some insight in to the process ?

**Comment by turadr** [comment]
How do you rebuild the NavMesh in order to take the modifier into account?
Methods that have names beginning with `BuildNavMesh...` will create the NavMesh data from scratch and this will take the maximum time.
On the other hand, methods whose names begin with `UpdateNavMesh...` will only update the NavMesh in parts/tiles where the sources or modifiers have changed. Thus the operation will take a fraction of the maximum time (depending on how much the environment changes, of course).

**Comment by ukwd** [comment]
@turadr   From what i understand though, if i place down a collider as a modifier and declare that area as "non walkable" or something, i have to rebuild the whole navmesh. Rather than just the areas it overlaps + their neighbours.

In unreal the way one asset did it, was creating a navmesh based on the modifier's data and then merging it with the preexisting main navmesh by first calculating which faces would need to be updated/changed. It made for a much faster solution for run time than updating the whole graph. I hope you can do something like this in the future.

**Comment by turadr** [comment]
`UpdateNavMesh...` methods are used with one whole NavMeshData object. They cannot operate on just a part of a NavMesh surface. That being said, they still check which tiles have changes in them since the last build and only generate those tiles. All the other tiles are left unprocessed and are preserved the way they are. (You can see the tiles displayed as the white lines of a regular grid across the NavMesh). For a large map, checking every time that anything has changed in each of the tile can accumulate to take a longer time than expected. Unfortunately there is no solution for that yet. We have in plan to implement a way to restrict the update to only a certain region/volume. That's for situations when you know there's no need to update anything outside that volume. I don't have a date for when this would be available.

Regarding the ability to merge parts of the NavMesh, it is not something that we plan to support any time soon.

**Comment by Hulkmaster** [comment]
2 years later any update on this?

I want to create gigantic map with ability for a player to build buildings on the map, and i will need to rebuild whole terrain's navmesh of each building placement - doesn't sound like a performance optimised solution

**Comment by turadr** [comment]
Starting with Untiy 2020.1 we've added the `bool` property `NavMeshBuildSettings.preserveTilesOutsideBounds` that, when set to `true`, allows `UpdateNavMeshData()` to build *only* the tiles that are *completely inside* the specified bounds while keeping the rest of the existing tiles untouched. In this way you can progressively build and update small sections of the NavMesh. If no sources are provided when updating an existing tile then that tile will be removed.
There is no documentation for this property right now, but I will add it some time soon.

**Comment by PixelSir** [comment]
> Starting with Untiy 2020.1 we've added the `bool` property `NavMeshBuildSettings.preserveTilesOutsideBounds` that, when set to `true`, allows `UpdateNavMeshData()` to build **only** the tiles that are **completely inside** the specified bounds while keeping the rest of the existing tiles untouched. In this way you can progressively build and update small sections of the NavMesh. If no sources are provided when updating an existing tile then that tile will be removed.
> There is no documentation for this property right now, but I will add it some time soon.

Will it be supporting multi threading or the job system?

**Comment by turadr** [comment]
> Will it be supporting multi threading or the job system?
`UpdateNavMeshData()` cannot be used with the job system but it is already executing multithreaded internally. In the Profiler data you can see in multiple worker threads the markers `NavMesh.TileMesh` and `NavMesh.HashTile` that represent the units of work for building the NavMesh.

For the foreseeable future we'll not add any implementation for building the NavMesh with the job system.

**Comment by Thaina** [comment]
> Starting with Untiy 2020.1 we've added the `bool` property `NavMeshBuildSettings.preserveTilesOutsideBounds` that, when set to `true`, allows `UpdateNavMeshData()` to build **only** the tiles that are **completely inside** the specified bounds while keeping the rest of the existing tiles untouched. In this way you can progressively build and update small sections of the NavMesh. If no sources are provided when updating an existing tile then that tile will be removed.
> There is no documentation for this property right now, but I will add it some time soon.

Sorry @turadr for resurrect old issue but it seem this still was not documented even in 2021 version. I would like to request that this issue should be kept opened as remider until the document about this `preserveTilesOutsideBounds` is already done

**Comment by turadr** [comment]
We are tracking internally the task about the missing documentation. There is no need to keep this thread active for that purpose. When we'll have an update we'll write here as well.

**Comment by Thaina** [comment]
@turadr The point is people didn't know about that and assume that it was not finished with no clues about why it is. Mark this issue as close without finished it also make ambiguous signal that is it just still be working on or it was rejected, while the information was kept internally

One solution might be expose the internal issue tracker to public, at least as readonly
