### ISSUE TITLE
can't use my name namespace in NavMeshSurface

### ISSUE THREAD

**Issue by xxhaithamxx** [Unity-Technologies/NavMeshComponents#96]
i have GameManager class that manage my data i tried to make NavMeshSurface access it but nothing worked even i tried to add namespace to GameManager

is there anyway i can make NavMeshSurface see my GameManager class ?

```
public class NavMeshSurface : MonoBehaviour { 
    private GameManager <--- can't find it 
    ....
}

public class GameManager{

    IDictionary<int, NavMeshSurface> m_NavMeshSurface = new Dictionary<int, NavMeshSurface>();

    private static GameManager m_Instance;
    private GameObject gameObject;
    public static GameManager Instance
    {
        get
        {
            if (m_Instance == null)
            {
                m_Instance = new GameManager();
                m_Instance.gameObject = new GameObject("_gameManager");
            }
            return m_Instance;
        }
    }
    public void BakeNavMeshSurface(int lvl)
    {
        NavMeshSurface result;
        if (m_NavMeshSurface.TryGetValue(lvl, out result)) result.BuildNavMesh();
    }
    public void AddNavMeshSurface(int lvl, NavMeshSurface meshSurface)
    {
        m_NavMeshSurface.Add(lvl, meshSurface);
    }
}
```

**Comment by turadr** [comment]
I think you need to add an assembly definition for your code and include that as a reference in the [`Assets\NavMeshComponents\Scripts\NavMeshComponents.asmdef`](https://github.com/Unity-Technologies/NavMeshComponents/blob/master/Assets/NavMeshComponents/Scripts/) file. This way the NavMeshComponents code will know about your classes.

Please have a look at the manual page for Assembly Definitions in Unity https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html .

As an example, [`NavMeshComponentsEditor.asmdef`](https://github.com/Unity-Technologies/NavMeshComponents/blob/master/Assets/NavMeshComponents/Editor/NavMeshComponentsEditor.asmdef) adds a reference to the NavMeshComponents asmdef so that the editor-only code can access the NavMeshSurface class.
